# Site settings
lang: ja
title: ysjj's pages
author: YAMASHITA, Junji
email: ysiijj+github@gmail.com

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
